http:
  routers:
    keycloak:
      entryPoints:
        - web
      rule: PathPrefix(`/auth`)
      service: keycloak
  services:
    keycloak:
      loadBalancer:
        servers:
          - url: http://keycloak:8080
